name: flyway
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flyway
    env:
      FLYWAY_USER: ${ username }
      FLYWAY_PASSWORD: ${ password }
      FLYWAY_URL: ${ dburl }
      FLYWAY_CLEAN_DISABLED: false
      FLYWAY_LOCATIONS: "filesystem:./totalcarefix/"
      flyway_environment: "totalcarefixdb"
      FLYWAY_CONFIG_FILES: "filesystem:./totalcarefix/flyway.toml"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyway CLI
        run: |
          sudo apt update
          sudo apt install -y default-jre
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.8.1/flyway-commandline-10.8.1-linux-x64.tar.gz | tar xvz
          sudo ln -s $(pwd)/flyway-10.8.1/flyway /usr/local/bin/flyway

      - name: Flyway Clean and Baseline
        run: |
          flyway clean
          flyway baseline

      - name: Flyway Migrate 
        run: flyway migrate 
